name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: "Get the repository content"
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"

    - name: Install dependecies
      run: python -m pip install -r test-requirements.txt

    - name: Check format
      run: |
        black .
    - name: Run tests
      run: python -m pytest